# Comments are provided throughout this file to help you get started.
# If you need more help, visit the Docker compose reference guide at
# https://docs.docker.com/go/compose-spec-reference/

services:
  fsbot:
    build: .
    container_name: fsbot-dev
    image: colinvdp/fsbot
    volumes:
      - ./FSBotData/Logs:/FSBotData/Logs/
    secrets:
      - source: config
        target: /app/config.ini
      - source: config_test
        target: /app/config_test.ini
      - source: google_service_account
        target: /app/service_account.json
    command: --loglevel=DEBUG --test=TRUE


secrets:
  config:
    file: config.ini
  config_test:
    file: config_test.ini
  google_service_account:
    file: service_account.json
